package tablero;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.GridLayout;

public class TableroGUI extends JFrame {
  public TableroGUI() {
    initComponents();
    this.setLocationRelativeTo(null);
    this.setTitle("Quoridor Game");
  }

  public void initComponents() {
    JPanel panel = new JPanel();
    // Fila 1
    JButton f101 = new JButton();
    JButton f102 = new JButton();
    JButton f103 = new JButton();
    JButton f104 = new JButton();
    JButton f105 = new JButton();
    JButton f106 = new JButton();
    JButton f107 = new JButton();
    JButton f108 = new JButton();
    JButton f109 = new JButton();
    JButton f110 = new JButton();
    JButton f111 = new JButton();
    JButton f112 = new JButton();
    JButton f113 = new JButton();
    JButton f114 = new JButton();
    JButton f115 = new JButton();
    JButton f116 = new JButton();
    JButton f117 = new JButton();
    // Fila 2
    JButton f201 = new JButton();
    JButton f202 = new JButton();
    JButton f203 = new JButton();
    JButton f204 = new JButton();
    JButton f205 = new JButton();
    JButton f206 = new JButton();
    JButton f207 = new JButton();
    JButton f208 = new JButton();
    JButton f209 = new JButton();
    JButton f210 = new JButton();
    JButton f211 = new JButton();
    JButton f212 = new JButton();
    JButton f213 = new JButton();
    JButton f214 = new JButton();
    JButton f215 = new JButton();
    JButton f216 = new JButton();
    JButton f217 = new JButton();
    // Fila 3
    JButton f301 = new JButton();
    JButton f302 = new JButton();
    JButton f303 = new JButton();
    JButton f304 = new JButton();
    JButton f305 = new JButton();
    JButton f306 = new JButton();
    JButton f307 = new JButton();
    JButton f308 = new JButton();
    JButton f309 = new JButton();
    JButton f310 = new JButton();
    JButton f311 = new JButton();
    JButton f312 = new JButton();
    JButton f313 = new JButton();
    JButton f314 = new JButton();
    JButton f315 = new JButton();
    JButton f316 = new JButton();
    JButton f317 = new JButton();
    // Fila 4
    JButton f401 = new JButton();
    JButton f402 = new JButton();
    JButton f403 = new JButton();
    JButton f404 = new JButton();
    JButton f405 = new JButton();
    JButton f406 = new JButton();
    JButton f407 = new JButton();
    JButton f408 = new JButton();
    JButton f409 = new JButton();
    JButton f410 = new JButton();
    JButton f411 = new JButton();
    JButton f412 = new JButton();
    JButton f413 = new JButton();
    JButton f414 = new JButton();
    JButton f415 = new JButton();
    JButton f416 = new JButton();
    JButton f417 = new JButton();
    // Fila 5
    JButton f501 = new JButton();
    JButton f502 = new JButton();
    JButton f503 = new JButton();
    JButton f504 = new JButton();
    JButton f505 = new JButton();
    JButton f506 = new JButton();
    JButton f507 = new JButton();
    JButton f508 = new JButton();
    JButton f509 = new JButton();
    JButton f510 = new JButton();
    JButton f511 = new JButton();
    JButton f512 = new JButton();
    JButton f513 = new JButton();
    JButton f514 = new JButton();
    JButton f515 = new JButton();
    JButton f516 = new JButton();
    JButton f517 = new JButton();
    // Fila 6
    JButton f601 = new JButton();
    JButton f602 = new JButton();
    JButton f603 = new JButton();
    JButton f604 = new JButton();
    JButton f605 = new JButton();
    JButton f606 = new JButton();
    JButton f607 = new JButton();
    JButton f608 = new JButton();
    JButton f609 = new JButton();
    JButton f610 = new JButton();
    JButton f611 = new JButton();
    JButton f612 = new JButton();
    JButton f613 = new JButton();
    JButton f614 = new JButton();
    JButton f615 = new JButton();
    JButton f616 = new JButton();
    JButton f617 = new JButton();
    // Fila 7
    JButton f701 = new JButton();
    JButton f702 = new JButton();
    JButton f703 = new JButton();
    JButton f704 = new JButton();
    JButton f705 = new JButton();
    JButton f706 = new JButton();
    JButton f707 = new JButton();
    JButton f708 = new JButton();
    JButton f709 = new JButton();
    JButton f710 = new JButton();
    JButton f711 = new JButton();
    JButton f712 = new JButton();
    JButton f713 = new JButton();
    JButton f714 = new JButton();
    JButton f715 = new JButton();
    JButton f716 = new JButton();
    JButton f717 = new JButton();
    // Fila 8
    JButton f801 = new JButton();
    JButton f802 = new JButton();
    JButton f803 = new JButton();
    JButton f804 = new JButton();
    JButton f805 = new JButton();
    JButton f806 = new JButton();
    JButton f807 = new JButton();
    JButton f808 = new JButton();
    JButton f809 = new JButton();
    JButton f810 = new JButton();
    JButton f811 = new JButton();
    JButton f812 = new JButton();
    JButton f813 = new JButton();
    JButton f814 = new JButton();
    JButton f815 = new JButton();
    JButton f816 = new JButton();
    JButton f817 = new JButton();
    // Fila 9
    JButton f901 = new JButton();
    JButton f902 = new JButton();
    JButton f903 = new JButton();
    JButton f904 = new JButton();
    JButton f905 = new JButton();
    JButton f906 = new JButton();
    JButton f907 = new JButton();
    JButton f908 = new JButton();
    JButton f909 = new JButton();
    JButton f910 = new JButton();
    JButton f911 = new JButton();
    JButton f912 = new JButton();
    JButton f913 = new JButton();
    JButton f914 = new JButton();
    JButton f915 = new JButton();
    JButton f916 = new JButton();
    JButton f917 = new JButton();
    // Fila 10
    JButton f1001 = new JButton();
    JButton f1002 = new JButton();
    JButton f1003 = new JButton();
    JButton f1004 = new JButton();
    JButton f1005 = new JButton();
    JButton f1006 = new JButton();
    JButton f1007 = new JButton();
    JButton f1008 = new JButton();
    JButton f1009 = new JButton();
    JButton f1010 = new JButton();
    JButton f1011 = new JButton();
    JButton f1012 = new JButton();
    JButton f1013 = new JButton();
    JButton f1014 = new JButton();
    JButton f1015 = new JButton();
    JButton f1016 = new JButton();
    JButton f1017 = new JButton();
    // Fila 11
    JButton f1101 = new JButton();
    JButton f1102 = new JButton();
    JButton f1103 = new JButton();
    JButton f1104 = new JButton();
    JButton f1105 = new JButton();
    JButton f1106 = new JButton();
    JButton f1107 = new JButton();
    JButton f1108 = new JButton();
    JButton f1109 = new JButton();
    JButton f1110 = new JButton();
    JButton f1111 = new JButton();
    JButton f1112 = new JButton();
    JButton f1113 = new JButton();
    JButton f1114 = new JButton();
    JButton f1115 = new JButton();
    JButton f1116 = new JButton();
    JButton f1117 = new JButton();
    // Fila 12
    JButton f1201 = new JButton();
    JButton f1202 = new JButton();
    JButton f1203 = new JButton();
    JButton f1204 = new JButton();
    JButton f1205 = new JButton();
    JButton f1206 = new JButton();
    JButton f1207 = new JButton();
    JButton f1208 = new JButton();
    JButton f1209 = new JButton();
    JButton f1210 = new JButton();
    JButton f1211 = new JButton();
    JButton f1212 = new JButton();
    JButton f1213 = new JButton();
    JButton f1214 = new JButton();
    JButton f1215 = new JButton();
    JButton f1216 = new JButton();
    JButton f1217 = new JButton();
    // Fila 13
    JButton f1301 = new JButton();
    JButton f1302 = new JButton();
    JButton f1303 = new JButton();
    JButton f1304 = new JButton();
    JButton f1305 = new JButton();
    JButton f1306 = new JButton();
    JButton f1307 = new JButton();
    JButton f1308 = new JButton();
    JButton f1309 = new JButton();
    JButton f1310 = new JButton();
    JButton f1311 = new JButton();
    JButton f1312 = new JButton();
    JButton f1313 = new JButton();
    JButton f1314 = new JButton();
    JButton f1315 = new JButton();
    JButton f1316 = new JButton();
    JButton f1317 = new JButton();
    // Fila 14
    JButton f1401 = new JButton();
    JButton f1402 = new JButton();
    JButton f1403 = new JButton();
    JButton f1404 = new JButton();
    JButton f1405 = new JButton();
    JButton f1406 = new JButton();
    JButton f1407 = new JButton();
    JButton f1408 = new JButton();
    JButton f1409 = new JButton();
    JButton f1410 = new JButton();
    JButton f1411 = new JButton();
    JButton f1412 = new JButton();
    JButton f1413 = new JButton();
    JButton f1414 = new JButton();
    JButton f1415 = new JButton();
    JButton f1416 = new JButton();
    JButton f1417 = new JButton();
    // Fila 15
    JButton f1501 = new JButton();
    JButton f1502 = new JButton();
    JButton f1503 = new JButton();
    JButton f1504 = new JButton();
    JButton f1505 = new JButton();
    JButton f1506 = new JButton();
    JButton f1507 = new JButton();
    JButton f1508 = new JButton();
    JButton f1509 = new JButton();
    JButton f1510 = new JButton();
    JButton f1511 = new JButton();
    JButton f1512 = new JButton();
    JButton f1513 = new JButton();
    JButton f1514 = new JButton();
    JButton f1515 = new JButton();
    JButton f1516 = new JButton();
    JButton f1517 = new JButton();
    // Fila 16
    JButton f1601 = new JButton();
    JButton f1602 = new JButton();
    JButton f1603 = new JButton();
    JButton f1604 = new JButton();
    JButton f1605 = new JButton();
    JButton f1606 = new JButton();
    JButton f1607 = new JButton();
    JButton f1608 = new JButton();
    JButton f1609 = new JButton();
    JButton f1610 = new JButton();
    JButton f1611 = new JButton();
    JButton f1612 = new JButton();
    JButton f1613 = new JButton();
    JButton f1614 = new JButton();
    JButton f1615 = new JButton();
    JButton f1616 = new JButton();
    JButton f1617 = new JButton();
    // Fila 17
    JButton f1701 = new JButton();
    JButton f1702 = new JButton();
    JButton f1703 = new JButton();
    JButton f1704 = new JButton();
    JButton f1705 = new JButton();
    JButton f1706 = new JButton();
    JButton f1707 = new JButton();
    JButton f1708 = new JButton();
    JButton f1709 = new JButton();
    JButton f1710 = new JButton();
    JButton f1711 = new JButton();
    JButton f1712 = new JButton();
    JButton f1713 = new JButton();
    JButton f1714 = new JButton();
    JButton f1715 = new JButton();
    JButton f1716 = new JButton();
    JButton f1717 = new JButton();

    panel.setLayout(new GridLayout(17, 17));
  }
}
